# Generated by Django 5.2.8 on 2025-11-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("path", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        max_length=150, verbose_name="Статус выполнения задачи"
                    ),
                ),
                ("params", models.JSONField()),
                ("result", models.JSONField(null=True)),
                ("error_message", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя ресурса")),
                (
                    "path",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Путь к ресурсу",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=None, null=True, verbose_name="Метаданные"
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(default=False, verbose_name="Ресурс устарел"),
                ),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        db_column="derived_from_resource_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="derived_resources",
                        to="timetable.resource",
                        verbose_name="Исходный ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурсы",
                "db_table": "resource",
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "mimetype",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=45,
                        null=True,
                        verbose_name="MIME-тип файла",
                    ),
                ),
                (
                    "url",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="URL-адрес файла",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания версии"
                    ),
                ),
                (
                    "last_changed",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                (
                    "hashsum",
                    models.CharField(max_length=255, verbose_name="Хэш-сумма файла"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_column="resource_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="timetable.resource",
                        verbose_name="Связанный ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия файла",
                "verbose_name_plural": "Версии файлов",
                "db_table": "file_version",
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "storage_type",
                    models.CharField(max_length=127, verbose_name="Тип хранилища"),
                ),
                (
                    "path",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Путь к файлу"
                    ),
                ),
                (
                    "download_url",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Ссылка для скачивания",
                    ),
                ),
                (
                    "resource_url",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Ссылка на ресурс",
                    ),
                ),
                (
                    "archive_url",
                    models.TextField(
                        null=True, verbose_name="Ссылка на папку с архивными версиями"
                    ),
                ),
                (
                    "file_version",
                    models.ForeignKey(
                        db_column="file_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storages",
                        to="timetable.fileversion",
                        verbose_name="Связанная версия файла",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хранилище",
                "verbose_name_plural": "Хранилища",
                "db_table": "storage",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название тега"),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=200, verbose_name="Название категории тега"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "db_table": "tag",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "category"), name="unique_name_category"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="resources",
                to="timetable.tag",
                verbose_name="Теги",
            ),
        ),
    ]
