"""
Django settings for timetable_project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# === ПУТИ ДЛЯ DOCKER ===
STATIC_URL = "/static/"
STATIC_ROOT = str(BASE_DIR / "staticfiles")  # Преобразуем в строку
STATICFILES_DIRS = [
    str(BASE_DIR / "static"),
]
print("BASE_DIR:", BASE_DIR)
print("STATICFILES_DIRS:", STATICFILES_DIRS)

# Папки для файлов
DATA_STORAGE_DIR = str(BASE_DIR / "staticfiles" / "files")
VIS_PATH = str(Path(DATA_STORAGE_DIR) / "ВИЗ")
GOOGLE_AUTH_FILE = str(BASE_DIR / "auth" / "google_drive_auth.json")

# Логи
LOG_DIR = str(BASE_DIR / "logs")
Path(LOG_DIR).mkdir(parents=True, exist_ok=True)

# Временные файлы
TEMP_DIR = str(BASE_DIR / "temp")
Path(TEMP_DIR).mkdir(parents=True, exist_ok=True)

# === БЕЗОПАСНОСТЬ ===
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-#q+2%evpem%e=)1^w$&3=zs2x6k608&sd^0o+@nr(676xhz_6x",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:81",
]

# Application definition
INSTALLED_APPS = [
    # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_apscheduler",
    "timetable",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CSRF_COOKIE_SECURE = False  # Для HTTP в dev, потом True в проде
SESSION_COOKIE_SECURE = False

ROOT_URLCONF = "timetable_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "timetable_project.wsgi.application"

# === БАЗА ДАННЫХ ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATABASE", "timetable"),
        "USER": os.getenv("MYSQL_USER", "django_user"),
        "PASSWORD": os.getenv("MYSQL_PASSWORD", "django_pass"),
        "HOST": os.getenv("MYSQL_HOST", "mysql_db"),
        "PORT": "3306",
    }
}

# === ВАЛИДАЦИЯ ПАРОЛЕЙ ===
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LOGIN_URL = "admin_login"
LOGIN_REDIRECT_URL = "admin_panel"

# === ЛОКАЛИЗАЦИЯ ===
LANGUAGE_CODE = "ru-ru"  # Лучше русский, раз ВИЗ на кириллице
TIME_ZONE = "Europe/Moscow"  # Или твоя зона
USE_I18N = True
USE_TZ = True

# === СТАТИКА И МЕДИА ===
MEDIA_URL = "/media/"
MEDIA_ROOT = str(BASE_DIR / "media")

# === ПОЧТА (если нужно) ===
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# === ЛОГИРОВАНИЕ ===
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "debug_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(Path(LOG_DIR) / "debug.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "info_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(Path(LOG_DIR) / "info.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,
            "formatter": "simple",
            "encoding": "utf-8",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(Path(LOG_DIR) / "errors.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 90,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["info_file", "error_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "timetable": {
            "handlers": ["debug_file", "info_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "": {
            "handlers": ["info_file", "error_file"],
            "level": "INFO",
        },
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
